// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";
import * as external0 from "@3sixty/data-json-ld";
import * as external1 from "../models/blobStorageCompressionType.js";
const MESSAGES = [
	"must NOT have fewer than 2 items",
	"must be equal to constant",
	"must be array",
	"must be string",
	"must be number",
	"must be boolean",
	"must be object"
];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the BlobStorageEntry schema.
 */
export const CompiledBlobStorageEntry: ICompiledValidator = validate52;
const keyword0 = external0["CompiledJsonLdContextDefinitionElement"];
const keyword2 = external0["CompiledJsonLdNodeObject"];
const keyword1 = Object.values(external1["BlobStorageCompressionType"]);

function validate53(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/blob-storage/BlobStorageCompressionType" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate53.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (!keyword1.includes(data)) {
		for (let i0 = 0; i0 < keyword1.length; i0++) {
			vErrors = pushError(
				vErrors,
				createError(
					instancePath,
					"#/anyOf" + "/" + i0 + "/const",
					"const",
					{ allowedValue: keyword1[i0] },
					"must be equal to constant"
				)
			);
			errors++;
		}
		vErrors = pushError(
			vErrors,
			createError(instancePath, "#/anyOf", "anyOf", {}, "must match a schema in anyOf")
		);
		errors++;
	}
	validate53.errors = vErrors;
	return errors === 0;
}
validate53.evaluated = { dynamicProps: false, dynamicItems: false };

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/blob-storage/BlobStorageEntry" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.id === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data.dateCreated === undefined) {
			const err3 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "dateCreated" },
				"must have required property '" + "dateCreated" + "'"
			);
			vErrors = pushError(vErrors, err3);
			errors++;
		}
		if (data.blobSize === undefined) {
			const err4 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "blobSize" },
				"must have required property '" + "blobSize" + "'"
			);
			vErrors = pushError(vErrors, err4);
			errors++;
		}
		if (data.integrity === undefined) {
			const err5 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "integrity" },
				"must have required property '" + "integrity" + "'"
			);
			vErrors = pushError(vErrors, err5);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err6 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						0
					);
					vErrors = pushError(vErrors, err6);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/blob-storage/" !== data0[0]) {
						const err7 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/blob-storage/" },
							1
						);
						vErrors = pushError(vErrors, err7);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/common/" !== data0[1]) {
						const err8 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							1
						);
						vErrors = pushError(vErrors, err8);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 2;
				if (!valid2) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs5 = errors;
						if (
							!keyword0(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs5 === errors;
					}
				}
			} else {
				const err9 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("BlobStorageEntry" !== data.type) {
				const err10 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "BlobStorageEntry" },
					1
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err11 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err12 = createError(
					instancePath + "/dateCreated",
					"#/properties/dateCreated/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err13 = createError(
					instancePath + "/dateModified",
					"#/properties/dateModified/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.blobSize !== undefined) {
			let data8 = data.blobSize;
			if (!(typeof data8 == "number" && isFinite(data8))) {
				const err14 = createError(
					instancePath + "/blobSize",
					"#/properties/blobSize/type",
					"type",
					{ type: "number" },
					4
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
		if (data.integrity !== undefined) {
			if (typeof data.integrity !== "string") {
				const err15 = createError(
					instancePath + "/integrity",
					"#/properties/integrity/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err15);
				errors++;
			}
		}
		if (data.encodingFormat !== undefined) {
			if (typeof data.encodingFormat !== "string") {
				const err16 = createError(
					instancePath + "/encodingFormat",
					"#/properties/encodingFormat/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err16);
				errors++;
			}
		}
		if (data.isEncrypted !== undefined) {
			if (typeof data.isEncrypted !== "boolean") {
				const err17 = createError(
					instancePath + "/isEncrypted",
					"#/properties/isEncrypted/type",
					"type",
					{ type: "boolean" },
					5
				);
				vErrors = pushError(vErrors, err17);
				errors++;
			}
		}
		if (data.compression !== undefined) {
			if (
				!validate53(data.compression, {
					instancePath: instancePath + "/compression",
					parentData: data,
					parentDataProperty: "compression",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
				errors = vErrors.length;
			}
		}
		if (data.fileExtension !== undefined) {
			if (typeof data.fileExtension !== "string") {
				const err18 = createError(
					instancePath + "/fileExtension",
					"#/properties/fileExtension/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err18);
				errors++;
			}
		}
		if (data.metadata !== undefined) {
			if (
				!keyword2(data.metadata, {
					instancePath: instancePath + "/metadata",
					parentData: data,
					parentDataProperty: "metadata",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
		if (data.blob !== undefined) {
			if (typeof data.blob !== "string") {
				const err19 = createError(
					instancePath + "/blob",
					"#/properties/blob/type",
					"type",
					{ type: "string" },
					3
				);
				vErrors = pushError(vErrors, err19);
				errors++;
			}
		}
	} else {
		const err20 = createError(instancePath, "#/type", "type", { type: "object" }, 6);
		vErrors = pushError(vErrors, err20);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: {
		"@context": true,
		type: true,
		id: true,
		dateCreated: true,
		dateModified: true,
		blobSize: true,
		integrity: true,
		encodingFormat: true,
		isEncrypted: true,
		compression: true,
		fileExtension: true,
		metadata: true,
		blob: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the BlobStorageCompressionType schema.
 */
export const CompiledBlobStorageCompressionType: ICompiledValidator = validate53;
